### ISSUE TITLE
Relay browser cookies from Firefox?

### ISSUE THREAD

**Issue by binarynoise** [binarynoise/open-in-mpv#10]
For some sites it would be cool to make mpv use browser cookies, so logins are kept.

This could be realized with extra actions (that would enable/disable this for a domain) or with a settings page.

**Comment by Joshix-1** [comment]
You can configure yt-dlp to use the cookies of the browser.

**Comment by binarynoise** [comment]
Sure, but that doesn't seem to be domain-specific
