### ISSUE TITLE
Please remember to update the version on the mozilla's addons webstore.

### ISSUE THREAD

**Issue by ghost** [binarynoise/open-in-mpv#3]
The version at https://addons.mozilla.org/en-US/firefox/addon/minimalist-open-in-mpv is still in version 1.0.5.

**Comment by Joshix-1** [comment]
thx, for the reminder

@binarynoise why is the version in manifest.json still 1.0.5?

**Comment by Joshix-1** [comment]
it doesn't look like anything has been changed: https://github.com/binarynoise/open-in-mpv/compare/v1.0.5..b86c5fbca2d6436c6f6959f702371c5c2068d15b

**Comment by binarynoise** [comment]
Yes, the browser addon didn't change since then.
I only increased the version to 1.0.5 (I don't know for what reason I did it after tagging the release) and reformatted.
The other changes are only related to the BetterDiscord plugin.
