### ISSUE TITLE
Getting https// instead of https:// in latest add-on January 24, 2024

### ISSUE THREAD

**Issue by drhashes** [binarynoise/open-in-mpv#4]
Thus failing to open URL..
This happened after update to firefox 122.0

Fixed it in mpv-scheme-handler.desktop

1. change `Exec=sh -c`
to `Exec=bash -c`

2. change `URL=${URL#mpv://};`
to `URL=${URL#mpv://}; URL=${URL//https/https:};`

**Comment by Joshix-1** [comment]
What is sh on your system? (Output of `ls -l /bin/sh` and `command -v`)

It should work if it's a mostly posix compatible shell like it should be.

**Comment by binarynoise** [comment]
> `URL=${URL//https/https:};`

I'll have a look at adding a general fix for other schemas (like http, file)

**Comment by binarynoise** [comment]
And I'll need to figure out how to notify the users of this change, the .desktop-file won't automatically be updated with the plugin.

**Comment by drhashes** [comment]
Hi guys,
great add-on!

I'm on ubuntu and bash understands URL=${URL//https/https:};
i.e. replacing https with https:

sh did not understand that and bash is standard everywhere today I believe.

ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Aug 28 18:55 /bin/sh -> dash

**Comment by Joshix-1** [comment]
F Bash. We want to be compatible with good shells like dash.

I think a better fix would be to append (and remove) `mpv://watch?` that shouldn't break in the future as every char should be valid in the query
