### ISSUE TITLE
Plugin Submission Denied

### ISSUE THREAD

**Issue by zerebos** [binarynoise/open-in-mpv#8]
Reason:
- `electron` package has been deprecated for use in plugins for a long while and is not allowed in new submissions
- Suggest using `window.open` such as used in [OpenInApp](https://github.com/fluzzeon/betterdiscord-OpenInApp/blob/2b1f7c2c05af8abb16529dc9c248a224a15492c3/OpenInApp.plugin.js)

Feel free to close this or reach out for more info.

**Comment by binarynoise** [comment]
Fixed in 592443c8 .

You may want the deprecation notice to the docs to avoid the confusion in the future.

**Comment by zerebos** [comment]
There is a deprecation notice in the docs already, but I will make it more prominent and clear. Please resubmit your plugin to the site and it should be approved.

**Comment by binarynoise** [comment]
Did the resubmission arrive at your end, @rauenzi?
