### ISSUE TITLE
Open In mpv fails to launch mpv if links contain an apostrophe

### ISSUE THREAD

**Issue by NikkSaan** [binarynoise/open-in-mpv#9]
The problem is with links from Odysee that contain the title of the video which often contains characters which need to be encoded/escaped.

Basically the same as my report for another similar extension [here](https://github.com/iina/iina/issues/4186). 

I don't have the time to debug this extension but since the symptoms are the same I think the solution should be the same as well.

---

fedora 40
firefox 125.0.2
open-in-mpv 2.1.0

**Comment by Joshix-1** [comment]
Yes, it's broken. Thanks for the report.

better example (not 404): [https://odysee.com/@rossmanngroup:a/helldivers-2-is-sony's-screw-you:7](https://odysee.com/@rossmanngroup:a/helldivers-2-is-sony's-screw-you:7)

`handlr open "mpv://watch#https://odysee.com/@rossmanngroup:a/helldivers-2-is-sony's-screw-you:7"` works. (normal xdg-open doesn't). But just escaping quotation marks in the js should fix it.

I doesn't seem like it's entirely our fault. Tried it in chromium and there it works.

**Comment by Joshix-1** [comment]
Fixed with https://github.com/binarynoise/open-in-mpv/releases/tag/v2.1.1
